version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    command: gunicorn --bind 0.0.0.0:5000 app:app --log-level info

    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis

  # celery_beat:
  #   build: .
  #   container_name: celery_beat
  #   command: celery -A app.celery beat --loglevel=info
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
