"""change nullable to be true

Revision ID: 24c26fa2d216
Revises: 68b10f5ee243
Create Date: 2025-09-15 12:25:44.784625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c26fa2d216'
down_revision = '68b10f5ee243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.alter_column('transaction_reference',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.alter_column('transaction_reference',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
