"""update_xtx

Revision ID: 27584c8c02e6
Revises: 6723ca712d7e
Create Date: 2025-09-18 12:45:46.271542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27584c8c02e6'
down_revision = '6723ca712d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('settlement_txn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_done', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement_txn', schema=None) as batch_op:
        batch_op.drop_column('date_done')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
