"""feat: update columns store more details

Revision ID: 2b3f9e884a73
Revises: 7f7e7a8a4318
Create Date: 2025-10-18 16:22:35.624818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3f9e884a73'
down_revision = '7f7e7a8a4318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('reservation_txn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_number', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reservation_txn_mpesa_number'), ['mpesa_number'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('idx_review_experience_created', ['experience_id', 'created_at'], unique=False)

    with op.batch_alter_table('settlement_txn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiving_mpesa_number', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('receiving_b2c_account', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_settlement_txn_receiving_mpesa_number'), ['receiving_mpesa_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement_txn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_txn_receiving_mpesa_number'))
        batch_op.drop_column('receiving_b2c_account')
        batch_op.drop_column('receiving_mpesa_number')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('idx_review_experience_created')

    with op.batch_alter_table('reservation_txn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_txn_mpesa_number'))
        batch_op.drop_column('mpesa_number')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
