"""feat collection-disbutsment

Revision ID: 3e411ade900f
Revises: af7241eb3ddc
Create Date: 2025-09-17 23:02:38.992159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e411ade900f'
down_revision = 'af7241eb3ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('reservation_refunds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_reference', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reservation_refunds_transaction_reference'), ['transaction_reference'], unique=True)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revocked', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reservations_revocked'), ['revocked'], unique=False)

    with op.batch_alter_table('settlement_txn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=False))
        batch_op.drop_index('ix_settlement_txn_approved_amount')
        batch_op.drop_index('ix_settlement_txn_request_amount')
        batch_op.drop_index('idx_settlement_platform_amount')
        batch_op.create_index('idx_settlement_platform_amount', ['platform', 'amount'], unique=False)
        batch_op.drop_index('idx_settlement_user_amount')
        batch_op.create_index('idx_settlement_user_amount', ['user_id', 'amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_txn_amount'), ['amount'], unique=False)
        batch_op.drop_column('approved_amount')
        batch_op.drop_column('request_amount')

    with op.batch_alter_table('users_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settlement_txn', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('applicable_fee', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fee_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.Numeric(precision=8, scale=2), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_ledger_balance'), ['balance'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ledger_fee_type'), ['fee_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ledger_settlement_txn'), ['settlement_txn'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_users_ledger_settlement_txn_settlement_txn'), 'settlement_txn', ['settlement_txn'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_ledger', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_ledger_settlement_txn_settlement_txn'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_ledger_settlement_txn'))
        batch_op.drop_index(batch_op.f('ix_users_ledger_fee_type'))
        batch_op.drop_index(batch_op.f('ix_users_ledger_balance'))
        batch_op.drop_column('description')
        batch_op.drop_column('balance')
        batch_op.drop_column('fee_type')
        batch_op.drop_column('applicable_fee')
        batch_op.drop_column('settlement_txn')

    with op.batch_alter_table('settlement_txn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_amount', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('approved_amount', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_settlement_txn_amount'))
        batch_op.drop_index('idx_settlement_user_amount')
        batch_op.create_index('idx_settlement_user_amount', ['user_id', 'approved_amount'], unique=False)
        batch_op.drop_index('idx_settlement_platform_amount')
        batch_op.create_index('idx_settlement_platform_amount', ['platform', 'approved_amount'], unique=False)
        batch_op.create_index('ix_settlement_txn_request_amount', ['request_amount'], unique=False)
        batch_op.create_index('ix_settlement_txn_approved_amount', ['approved_amount'], unique=False)
        batch_op.drop_column('amount')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_revocked'))
        batch_op.drop_column('revocked')

    with op.batch_alter_table('reservation_refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_refunds_transaction_reference'))
        batch_op.drop_column('transaction_reference')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
