"""nullable bio

Revision ID: 567f6c45223b
Revises: 5027face9bfb
Create Date: 2025-09-13 14:26:02.235258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567f6c45223b'
down_revision = '5027face9bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avator_url',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('avator_url',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
