"""create new indexes on reservation

Revision ID: 582e210f23e7
Revises: 3a63255e739b
Create Date: 2025-09-21 14:42:59.421841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582e210f23e7'
down_revision = '3a63255e739b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index('idx_reservations_experience_id', ['experience_id'], unique=False)
        batch_op.create_index('idx_reservations_id', ['id'], unique=False)
        batch_op.create_index('idx_reservations_slot_id', ['slot_id'], unique=False)
        batch_op.create_index('idx_reservations_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index('idx_reservations_user_id')
        batch_op.drop_index('idx_reservations_slot_id')
        batch_op.drop_index('idx_reservations_id')
        batch_op.drop_index('idx_reservations_experience_id')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
