"""upgrade reservation_refund

Revision ID: 5a4509272471
Revises: be387f864180
Create Date: 2025-09-16 13:21:33.520709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4509272471'
down_revision = 'be387f864180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_disbursements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('mpesa_checkout_request_id', sa.Text(), nullable=True),
    sa.Column('transaction_reference', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('mpesa_number', sa.Text(), nullable=False),
    sa.Column('disbursement_type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_disbursements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_disbursements'))
    )
    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_disbursements_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_disbursements_disbursement_type'), ['disbursement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_disbursements_mpesa_checkout_request_id'), ['mpesa_checkout_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_disbursements_mpesa_number'), ['mpesa_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_disbursements_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_disbursements_transaction_reference'), ['transaction_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_disbursements_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('reservation_refunds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('mpesa_number', sa.Text(), nullable=False))
        batch_op.drop_index('ix_reservation_refunds_amount')
        batch_op.drop_index('idx_refunds_pending', postgresql_where="((status)::text = 'pending'::text)")
        batch_op.create_index('idx_refunds_pending', ['requested_amount', 'reservation_id'], unique=False, postgresql_where=sa.text("status = 'pending'"))
        batch_op.create_index(batch_op.f('ix_reservation_refunds_approved_amount'), ['approved_amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_refunds_mpesa_number'), ['mpesa_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_refunds_requested_amount'), ['requested_amount'], unique=False)
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_refunds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_reservation_refunds_requested_amount'))
        batch_op.drop_index(batch_op.f('ix_reservation_refunds_mpesa_number'))
        batch_op.drop_index(batch_op.f('ix_reservation_refunds_approved_amount'))
        batch_op.drop_index('idx_refunds_pending', postgresql_where=sa.text("status = 'pending'"))
        batch_op.create_index('idx_refunds_pending', ['amount', 'reservation_id'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
        batch_op.create_index('ix_reservation_refunds_amount', ['amount'], unique=False)
        batch_op.drop_column('mpesa_number')
        batch_op.drop_column('approved_amount')
        batch_op.drop_column('requested_amount')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_disbursements_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_disbursements_transaction_reference'))
        batch_op.drop_index(batch_op.f('ix_api_disbursements_status'))
        batch_op.drop_index(batch_op.f('ix_api_disbursements_mpesa_number'))
        batch_op.drop_index(batch_op.f('ix_api_disbursements_mpesa_checkout_request_id'))
        batch_op.drop_index(batch_op.f('ix_api_disbursements_disbursement_type'))
        batch_op.drop_index(batch_op.f('ix_api_disbursements_amount'))

    op.drop_table('api_disbursements')
    # ### end Alembic commands ###
