"""update mpesa_

Revision ID: 907f8fb7ecfc
Revises: 5a4509272471
Create Date: 2025-09-16 13:23:28.009288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907f8fb7ecfc'
down_revision = '5a4509272471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.alter_column('mpesa_number',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.alter_column('mpesa_number',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
