"""feat: redund id fix

Revision ID: af7241eb3ddc
Revises: 907f8fb7ecfc
Create Date: 2025-09-16 13:27:13.577812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7241eb3ddc'
down_revision = '907f8fb7ecfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_api_disbursements_refund_id'), ['refund_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_api_disbursements_refund_id_reservation_refunds'), 'reservation_refunds', ['refund_id'], ['id'])

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_api_disbursements_refund_id_reservation_refunds'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_api_disbursements_refund_id'))
        batch_op.drop_column('refund_id')

    # ### end Alembic commands ###
