"""add reservation_id to collection api

Revision ID: be387f864180
Revises: 2a9fbe40f303
Create Date: 2025-09-15 22:10:07.386836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be387f864180'
down_revision = '2a9fbe40f303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_api_collections_reservation_id'), ['reservation_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_api_collections_reservation_id_reservations'), 'reservations', ['reservation_id'], ['id'])

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_api_collections_reservation_id_reservations'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_api_collections_reservation_id'))
        batch_op.drop_column('reservation_id')

    # ### end Alembic commands ###
