"""fx add status to o stlmt txn

Revision ID: e9378b230b50
Revises: 27584c8c02e6
Create Date: 2025-09-18 20:39:08.910129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9378b230b50'
down_revision = '27584c8c02e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('settlement_txn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Text(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_settlement_txn_status'), ['status'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement_txn', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_settlement_txn_status'), type_='unique')
        batch_op.drop_column('status')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
