"""add mpesa

Revision ID: eb112c8224e1
Revises: 24c26fa2d216
Create Date: 2025-09-15 12:31:45.144810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb112c8224e1'
down_revision = '24c26fa2d216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_checkout_request_id', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_api_collections_mpesa_checkout_request_id'), ['mpesa_checkout_request_id'], unique=True)

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_collections_mpesa_checkout_request_id'))
        batch_op.drop_column('mpesa_checkout_request_id')

    # ### end Alembic commands ###
