"""Fix user model defaults and nullable columns

Revision ID: f3441d16c9cf
Revises: de2157febdd5
Create Date: 2025-09-13 14:19:38.241652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3441d16c9cf'
down_revision = 'de2157febdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_method_default_method'), ['default_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_method_mpesa_number'), ['mpesa_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_method_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('default')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_payment_method_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_method_mpesa_number'))
        batch_op.drop_index(batch_op.f('ix_payment_method_default_method'))

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
