"""add times to slots

Revision ID: f7fd96bb185e
Revises: 7f0224e4bc3e
Create Date: 2025-09-14 22:47:31.622481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fd96bb185e'
down_revision = '7f0224e4bc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')

    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.Time(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=False))
        batch_op.create_index('idx_slots_time_range', ['date', 'start_time', 'end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_slots_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_slots_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slots_start_time'))
        batch_op.drop_index(batch_op.f('ix_slots_end_time'))
        batch_op.drop_index('idx_slots_time_range')
        batch_op.drop_column('timezone')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index('idx_experiences_search', postgresql_using='gin')
        batch_op.create_index('idx_experiences_search', [sa.text("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
